apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-claim
  namespace: mini-projet
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 2Gi
