apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mysql-deploy
  name: mysql-deploy
  namespace: mini-projet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql-deploy
    spec:
          containers:
          - env:
            - name: MYSQL_DATABASE
              value: wordpress
            - name: MYSQL_USER
              value: wordpress
            - name: MYSQL_PASSWORD
              value: wordpress
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: "1"
            image: mysql:5.7
            name: mysql
            ports:
            - containerPort: 3306
            resources: {}
            volumeMounts:
               - name: mysql-persistent-storage
                 mountPath: /var/lib/mysql
          volumes:
          - name: mysql-persistent-storage
            hostPath:
               path: /data/mysql
status: {}
