apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: wordpress-deploy
  name: wordpress-deploy
  namespace: mini-projet
spec:
  ports:
  - port: 12000
    protocol: TCP
    targetPort: 80
    nodePort: 30100
  selector:
    app: wordpress-deploy
  type: NodePort
status:
  loadBalancer: {}
